# coding: utf-8

import pygame

# Colors
BLACK = (0, 0, 0)
DARK_GREY = (33, 33, 33)
GREY = (127, 127, 127)
LIGHT_GREY = (192, 192, 192)
WHITE = (255, 255, 255)
COLOR_BG = (24, 25, 20)
COLOR_GRID = DARK_GREY
COLOR_DEFEAT = (255, 33, 33)
COLOR_SCORE = (255, 255, 33)
COLOR_APPLE_SKIN = (255, 127, 127)
COLOR_APPLE_BODY = (255, 66, 66)
COLOR_SNAKE_SKIN = (33, 255, 33)
COLOR_SNAKE_BODY = (33, 192, 33)
COLOR_SNAKE_HEAD = (192, 192, 33)
COLOR_DEAD_SNAKE_SKIN = LIGHT_GREY
COLOR_DEAD_SNAKE_BODY = GREY
COLOR_DEAD_SNAKE_HEAD = DARK_GREY

# Keys
KEY_EXIT = pygame.K_ESCAPE
KEY_UP = pygame.K_UP
KEY_RIGHT = pygame.K_RIGHT
KEY_DOWN = pygame.K_DOWN
KEY_LEFT = pygame.K_LEFT
KEY_PAUSE = pygame.K_SPACE
KEY_REBORN = pygame.K_r

# Game parameters
GAME_NAME = "Snake Game"
SCREEN_SIZE = SCREEN_WIDTH, SCREEN_HEIGHT = (640, 480)
CELL_SIZE = 20
COLS = SCREEN_WIDTH // CELL_SIZE
ROWS = SCREEN_HEIGHT // CELL_SIZE
UP, DOWN, LEFT, RIGHT = (0, -1), (0, 1), (-1, 0), (1, 0)
DISPLAY_MODE = pygame.HWSURFACE | pygame.DOUBLEBUF
LOOP_SPEED = 30
ICON = "resources/pysnake.png"
FONT_NAME = "resources/Minecraft.ttf"
FONT_SIZE = 20
SOUND_EAT = "resources/eat.wav"
SOUND_HIT = "resources/hit.wav"

# Snake default settings
SNAKE_INIT_X = 0
SNAKE_INIT_Y = 0
SNAKE_INIT_BODY_SIZE = 5
SNAKE_INIT_DIRECTION = RIGHT
SNAKE_INIT_SPEED = 10
